### ISSUE TITLE
Error: TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by alfonso-paella** [context-labs/autodoc#18]
I did a fresh install with yarn the project, and cloned a repo we had with the indices precomputed. Then imported the env var and ran `doc q`

Error:
```
TypeError: Cannot read properties of undefined (reading 'length')
    at makeQAPrompt (file:///Users/alfongj/.config/yarn/global/node_modules/@context-labs/autodoc/dist/cli/commands/query/createChatChain.js:26:14)
    at makeChain (file:///Users/alfongj/.config/yarn/global/node_modules/@context-labs/autodoc/dist/cli/commands/query/createChatChain.js:47:23)
    at query (file:///Users/alfongj/.config/yarn/global/node_modules/@context-labs/autodoc/dist/cli/commands/query/index.js:25:19)
```

**Comment by samheutmaker** [comment]
You need to run `doc user` to configure you're query config.

**Comment by Klaudioz** [comment]
I interacted with one project without any issues few days ago. I came back today and I'm getting this error.

Should I run this command every time?

`A user configureation already exists. It will be overwritten. Do you want to continue? (y/N)`
