### ISSUE TITLE
ReferenceError: Headers is not defined

### ISSUE THREAD

**Issue by creatorrr** [context-labs/autodoc#4]
Tried running autodoc on a fresh repository and got this error at indexing time.

Steps to reproduce:
1. `doc init`  to create an `autodoc.config.json` file (contents pasted below)
2. Run `doc index` and answer yes at the prompt

**Stacktrace**:

```node
ReferenceError: Headers is not defined
    at createRequest (file:///home/diwank/.fnm/node-versions/v17.9.1/installation/lib/node_modules/@context-labs/autodoc/node_modules/langchain/dist/util/axios-fetch-adapter.js:
234:21)
    at fetchAdapter (file:///home/diwank/.fnm/node-versions/v17.9.1/installation/lib/node_modules/@context-labs/autodoc/node_modules/langchain/dist/util/axios-fetch-adapter.js:1
64:21)
    at dispatchRequest (/home/diwank/.fnm/node-versions/v17.9.1/installation/lib/node_modules/@context-labs/autodoc/node_modules/axios/lib/core/dispatchRequest.js:58:10)
    at Axios.request (/home/diwank/.fnm/node-versions/v17.9.1/installation/lib/node_modules/@context-labs/autodoc/node_modules/axios/lib/core/Axios.js:108:15)
    at Function.wrap [as request] (/home/diwank/.fnm/node-versions/v17.9.1/installation/lib/node_modules/@context-labs/autodoc/node_modules/axios/lib/helpers/bind.js:9:15)
    at /home/diwank/.fnm/node-versions/v17.9.1/installation/lib/node_modules/@context-labs/autodoc/node_modules/openai/dist/common.js:149:22
    at /home/diwank/.fnm/node-versions/v17.9.1/installation/lib/node_modules/@context-labs/autodoc/node_modules/openai/dist/api.js:1738:133
    at runNextTicks (node:internal/process/task_queues:61:5)
    at listOnTimeout (node:internal/timers:528:9)
    at processTimers (node:internal/timers:502:7)
Failed to get summary for file turbo.py

```

*****

**autodoc.config.json**:
```json
{
  "name": "turbo-chat",
  "repositoryUrl": "https://github.com/creatorrr/turbo-chat",
  "root": ".",
  "output": "./.autodoc",
  "llms": [
    "gpt-3.5-turbo",
    "gpt-4"
  ],
  "ignore": [
    ".*",
    "*package-lock.json",
    "*package.json",
    "node_modules",
    "*dist*",
    "*build*",
    "*test*",
    "*.svg",
    "*.md",
    "*.mdx",
    "*.toml",
    "*autodoc*"
  ]
}
```

**Comment by creatorrr** [comment]
`doc -V`
0.0.7

**Comment by creatorrr** [comment]
Possibly duplicate of #3

**Comment by samheutmaker** [comment]
Upgrade to node 18 or high.

**Comment by Bewinxed** [comment]
> Upgrade to node 18 or high.

Fixed, it runs now but it gives [TOO MANY REQUESTS] on indexing

**Comment by creatorrr** [comment]
gotcha yeah, upgrading to node 18 fixed it. Closing
